Repository ZigZagExchange/frontend, pull requests merged in 2022-07, with the labels that each got.

#673 #663
  src/components/organisms/TradeDashboard/TradeBooks/OrdersBook.js
  src/components/organisms/TradeDashboard/TradeBooks/TradePriceHeadSecond/TradePriceHeadSecond.jsx
  src/components/organisms/TradeDashboard/TradeMarketSelector/TradeRatesCard/TradeRatesCard.jsx
Labels: uiRedesign, priority

#676 #597
  package.json
  src/components/molecules/Button/ConnectWalletButton.jsx
  src/components/molecules/Button/index.js
  src/components/molecules/HighSlippageModal/HighSlippageModal.jsx
  src/components/molecules/HighSlippageModal/index.js
  src/components/molecules/SpotForm/SpotForm.jsx
  src/components/molecules/SpotForm/index.js
  src/components/organisms/TradeDashboard/TradeDashboard.js
  src/components/organisms/TradeDashboard/TradeTables/TradeTables.js
  src/lib/store/features/api/apiSlice.js
Labels: uiRedesign, priority

#706 #687 #689
  src/components/organisms/TradeDashboard/TradeTables/OrdersTable/OrdersTable.jsx
Labels: uiRedesign

#707 #685
  src/components/molecules/Dropdown/Dropdown.jsx
  src/components/organisms/Header/Header.jsx
Labels: uiRedesign, priority

#714 #699
  src/components/pages/SwapPage/SwapContainer/SwapContianer.js
  src/components/pages/SwapPage/SwapPage.jsx
Labels: uiRedesign, priority

#712 #708 #696 #688
  src/components/organisms/TradeDashboard/TradeBooks/OrdersBook.js
  src/components/organisms/TradeDashboard/TradeBooks/TradePriceTable/TradePriceTable.jsx
  src/components/organisms/TradeDashboard/TradeDashboard.js
Labels: uiRedesign, priority

#700 issue #694: fix firefox scrollbars on trade page
  src/components/organisms/TradeDashboard/TradeBooks/TradePriceTable/TradePriceTable.css
  src/components/organisms/TradeDashboard/TradeBooks/TradePriceTable/TradePriceTable.jsx
  src/components/organisms/TradeDashboard/TradeBooks/TradeRecentTable/TradeRecentTable.css
  src/components/organisms/TradeDashboard/TradeBooks/TradeRecentTable/TradeRecentTable.jsx
  src/components/organisms/TradeDashboard/TradeSidebar/TradeSidebar.js
Labels: uiRedesign

#701 issue #690: add icons, Arbitrum Soon
  src/assets/images/networks/arbitrum-network.svg
  src/assets/images/networks/zksync-network.svg
  src/components/molecules/Dropdown/Dropdown.jsx
  src/components/organisms/Header/Header.jsx
  src/components/organisms/NetworkSelection/NetworkSelection.jsx
  src/components/organisms/NetworkSelection/index.js
Labels: uiRedesign

#723 #477
  src/components/organisms/TradeDashboard/TradeDashboard.js
  src/components/organisms/TradeDashboard/TradeMarketSelector/TradeRatesCard/TradeRatesCard.jsx
  src/components/pages/SwapPage/SwapPage.jsx
  src/lib/api/API.js
Labels: uiRedesign

#711 Fix/issue: #693
  src/components/organisms/TokenDropdownModal/TokenDropDownModal.jsx
  src/components/pages/SwapPage/SwapContainer/SwapContianer.js
  src/components/pages/SwapPage/SwapPage.jsx
  src/components/pages/SwapPage/TransationSettings/TransactionSettings.jsx
Labels: uiRedesign, priority

#762 fix issue #750: scrollbar visibility
  src/components/molecules/Dropdown/TokenPairDropdown.jsx
Labels: uiRedesign

#728 #492
  src/components/pages/BridgePage/BridgeContainer/BridgeContainer.jsx
  src/components/pages/SwapPage/SwapPage.jsx
Labels: uiRedesign

#859 #810
  src/components/atoms/RangeSlider/RangeSlider.jsx
  src/components/molecules/SpotForm/SpotForm.jsx
Labels: feature
